export const GET_EXCHANGE_RATE = "GET_EXCHANGE_RATE";
export const GET_EUR_EXCHANGE_RATE = "GET_EUR_EXCHANGE_RATE";
export const GET_USD_EXCHANGE_RATE = "GET_USD_EXCHANGE_RATE";
export const SET_LOADING = "SET_LOADING";
