export const GET_EXCHANGE_RATE = "GET_EXCHANGE_RATE";
export const GET_EUR_EXCHANGE_RATE = "GET_EUR_EXCHANGE_RATE";
export const GET_USD_EXCHANGE_RATE = "GET_USD_EXCHANGE_RATE";
export const SET_LOADING = "SET_LOADING";

export const SET_USD_VALUE = "SET_USD_VALUE";
export const SET_USD_UAH_VALUE = "SET_USD_UAH_VALUE";
export const SET_EUR_VALUE = "SET_EUR_VALUE";
export const SET_EUR_UAH_VALUE = "SET_EUR_UAH_VALUE";
