export const GET_EXCHANGE_RATE = "GET_EXCHANGE_RATE";
export const GET_EUR_EXCHANGE_RATE = "GET_EUR_EXCHANGE_RATE";
export const GET_USD_EXCHANGE_RATE = "GET_USD_EXCHANGE_RATE";
export const GET_GBP_EXCHANGE_RATE = "GET_GBP_EXCHANGE_RATE";
export const SET_LOADING = "SET_LOADING";

export const SET_USD_VALUE = "SET_USD_VALUE";
export const SET_USD_UAH_VALUE = "SET_USD_UAH_VALUE";
export const SET_EUR_VALUE = "SET_EUR_VALUE";
export const SET_EUR_UAH_VALUE = "SET_EUR_UAH_VALUE";
export const SET_GBP_VALUE = "SET_GBP_VALUE";
export const SET_GBP_UAH_VALUE = "SET_GBP_UAH_VALUE";

export const GET_CUSTOM_EXCHANGE_RATE = "GET_CUSTOM_EXCHANGE_RATE";
export const SET_FIRST_CURRENCY = "SET_FIRST_CURRENCY";
export const SET_SECOND_CURRENCY = "SET_SECOND_CURRENCY";
export const SET_FIRST_CURRENCY_NAME = "SET_FIRST_CURRENCY_NAME";
export const SET_SECOND_CURRENCY_NAME = "SET_SECOND_CURRENCY_NAME";
